RENDER: True
OBSERVATION_DIMENSION : [128, 128, 3]
# Number of outputs
OUTPUTS :  2
# use orientation offset to the spawn position in degrees
SPAWN_ROT_OFFSET : 20
SPAWN_POS_OFFSET : 0.5
# Crop the image
CROPIMAGE : False
# Pixels to crop image to (or if not copping, the maximum and minimum pixels of the image)
FROM_X :  0  # 24
TO_X : 128     # 72
FROM_Y : 0   # 36
TO_Y : 128     # 84
# Number of layers of the image of the environment observation
IMAGE_LAYERS: 5
# Meanshift the image?
MEANSHIFT : True
# Greyscale the image?
GRAYSCALE : False
# How manz samples to collect before optimiyation in the VAE starts
VAE_LEARNING_START : 256
# vae batch size
VAE_BATCH_SIZE : 64
# vae replay buffer size
VAE_REPLAY_BUFFER_SIZE: 10000
# Number of GPUS for the VAE
VAE_NUM_GPUS : 0

# Since we connect to LGSVL via a websocket, we need to share an interface to it per node running the simulation
SHARED_SIMULATOR_INTERFACE : True
DISABLE_ENV_CHECKING : True